[2021-11-12 11:42:42,035: INFO/Process-1] Connected to redis://localhost:6379/0
[2021-11-12 11:42:42,074: INFO/Process-1] mingle: searching for neighbors
[2021-11-12 11:42:43,106: INFO/Process-1] mingle: all alone
[2021-11-12 11:42:43,131: INFO/Process-1] celery@fragmenter ready.
[2021-11-12 11:48:41,796: INFO/Process-1] Task openff.bespokefit.executor.services.fragmenter.worker.fragment[452a3da6-cca0-4b85-a47c-d9a34441edc0] received
[2021-11-12 11:48:42,414: ERROR/ForkPoolWorker-1] Task openff.bespokefit.executor.services.fragmenter.worker.fragment[452a3da6-cca0-4b85-a47c-d9a34441edc0] raised unexpected: RuntimeError('\n')
Traceback (most recent call last):
  File "/Users/daniellebergaziin/anaconda/envs/bespoke/lib/python3.9/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/daniellebergaziin/anaconda/envs/bespoke/lib/python3.9/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/daniellebergaziin/anaconda/envs/bespoke/lib/python3.9/site-packages/openff/bespokefit/executor/services/fragmenter/worker.py", line 26, in fragment
    return fragmenter.fragment(molecule, target_bond_smarts=target_bond_smarts).json()
  File "/Users/daniellebergaziin/anaconda/envs/bespoke/lib/python3.9/site-packages/openff/fragmenter/fragment.py", line 916, in fragment
    result = self._fragment(molecule, target_bond_smarts)
  File "/Users/daniellebergaziin/anaconda/envs/bespoke/lib/python3.9/site-packages/openff/fragmenter/fragment.py", line 1012, in _fragment
    molecule = assign_elf10_am1_bond_orders(
  File "/Users/daniellebergaziin/anaconda/envs/bespoke/lib/python3.9/site-packages/openff/fragmenter/chemi.py", line 42, in assign_elf10_am1_bond_orders
    molecule.apply_elf_conformer_selection()
  File "/Users/daniellebergaziin/anaconda/envs/bespoke/lib/python3.9/site-packages/openff/toolkit/topology/molecule.py", line 3361, in apply_elf_conformer_selection
    toolkit_registry.call(
  File "/Users/daniellebergaziin/anaconda/envs/bespoke/lib/python3.9/site-packages/openff/toolkit/utils/toolkit_registry.py", line 366, in call
    raise e
  File "/Users/daniellebergaziin/anaconda/envs/bespoke/lib/python3.9/site-packages/openff/toolkit/utils/toolkit_registry.py", line 362, in call
    return method(*args, **kwargs)
  File "/Users/daniellebergaziin/anaconda/envs/bespoke/lib/python3.9/site-packages/openff/toolkit/utils/openeye_wrapper.py", line 1776, in apply_elf_conformer_selection
    raise RuntimeError("\n" + output_string)
RuntimeError: 

